## Linear Regression: 1 Input + 1 Output
- Linear Regression has one input and one output only

# Formula for prediction is, y = mX + c

# Linear Regression On Salary DataSet

In [1]:
# import the libraries
import numpy as np
import pandas as pd 
import seaborn as sns

In [2]:
# load the Salaries Dataset
df = pd.read_csv('Salary_Data.csv')
df.head(2)

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0

##### Objective: Predict the Salary of an employee on the basis of Years of Experience he/she has


In [5]:
# now, lets separate / build input and output data ie X and y values 
# input: X
X = df[['YearsExperience']]
X[:2]

YearsExperience
0              1.1
1              1.3

In [6]:
# output: y
y = df.Salary
y[:2]

0    39343.0
1    46205.0
Name: Salary, dtype: float64

## STEP 1: Training Phase

In [7]:
# import LinearRegression model from sci-kit learn library(sklearn)
from sklearn.linear_model import LinearRegression

In [10]:
# now crate a model (variable) for LinearRegression()
model = LinearRegression()
model

LinearRegression()

In [12]:
# Now, for Training phase call fit() method 
model.fit(X,y) #training process

LinearRegression()

## STEP 2: Testing Phase

In [13]:
# Now, for Testing Phase, use/call predict() method
# we predict the Salary of a Fresher candidate
#in predict will supply Experience(input/s) then it will give Salary
# as fresher we have zero YearsExperience 
model.predict([[0]])

C:\Users\abhis\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([25792.20019867])

In [15]:
df[:3]

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0

In [16]:
model.predict([[1.1], [1.3], [1.5]])

C:\Users\abhis\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([36187.15875227, 38077.15121656, 39967.14368085])

In [18]:
# Now, check the score of X and y 
model.score(X,y)*100

95.69566641435085

In [19]:
df.describe()

YearsExperience         Salary
count        30.000000      30.000000
mean          5.313333   76003.000000
std           2.837888   27414.429785
min           1.100000   37731.000000
25%           3.200000   56720.750000
50%           4.700000   65237.000000
75%           7.700000  100544.750000
max          10.500000  122391.000000

In [20]:
# Lets check/predict salary for 22 Years of Experience 
model.predict([[22]])

C:\Users\abhis\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([233691.37127068])

In [21]:
df.shape

(30, 2)

In [22]:
# Testing input(data) and output(y_pred) 
data = [[1],[2.3],[4],[5.8],[8],[9.2],[10.9]] #input
y_pred = model.predict(data) #output
y_pred

C:\Users\abhis\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([ 35242.16252012,  47527.11353802,  63592.04948449,  80601.98166311,
       101391.89877031, 112731.85355606, 128796.78950253])

In [24]:
# Best fit line means, Line of Testing input data + output of it
# Best fit line accuracy score is always 100%
model.score(data, y_pred)*100

C:\Users\abhis\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


100.0

In [ ]:
# both will give you prediction line/Best fit line 
import matplotlib.pyplot as plt
plt.plot(data, y_pred, '', label='Predicted Salary(Best Fit Line)')
sns.scatterplot(x='YearsExperience',y='Salary',data=df)
